# This rule is not used by the project candor itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to candor.dev resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: candor
    app.kubernetes.io/managed-by: kustomize
  name: suppression-viewer-role
rules:
- apiGroups:
  - candor.dev
  resources:
  - suppressions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - candor.dev
  resources:
  - suppressions/status
  verbs:
  - get
