apiVersion: candor.candor.dev/v1alpha1
kind: SignalPolicy
metadata:
  labels:
    app.kubernetes.io/name: candor
    app.kubernetes.io/managed-by: kustomize
  name: signalpolicy-sample
spec:
  # TODO(user): Add fields here
