{{- if .Values.rbac.helpers.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
{{- if .Values.rbac.namespaced }}
kind: Role
{{- else }}
kind: ClusterRole
{{- end }}
metadata:
{{- if .Values.rbac.namespaced }}
  namespace: {{ .Release.Namespace }}
{{- end }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ include "candor.name" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  name: {{ include "candor.resourceName" (dict "suffix" "signalpolicy-admin-role" "context" $) }}
rules:
- apiGroups:
  - candor.dev
  resources:
  - signalpolicies
  verbs:
  - '*'
- apiGroups:
  - candor.dev
  resources:
  - signalpolicies/status
  verbs:
  - get
{{- end }}
