{{/*
A separate file from _helpers.tpl, not an addition to it - _helpers.tpl is kubebuilder's own
generated partial and gets wholesale-regenerated by `kubebuilder edit --plugins=helm/v2-alpha
--force` the same way values.yaml does (see CONTRIBUTING.md); a plain custom template file the
plugin has never heard of is untouched by that regeneration.
*/}}

{{/*
Validates and parses a port value strictly, failing chart rendering with a clear message instead
of Sprig's own `int` cast (spf13/cast under the hood) silently miscoercing it - three distinct ways
that can go wrong, all confirmed by rendering the chart with each input during review before this
helper existed:
  - a non-numeric value (e.g. "944e", a plausible --set-string typo) silently becomes 0
  - a leading zero (e.g. "010") is reinterpreted as octal by strconv's base-0 parsing (010 -> 8)
  - a value too large for an int silently overflows to 0
The regex below (optional minus, then either a bare "0" or 1-5 digits not starting with 0) rejects
all three: no leading-zero form other than "0" itself can match, and capping at 5 digits keeps
every value that does match comfortably within int range, so `int` can never silently overflow one
that passed validation. Takes a dict with:
  - .value: the raw value to validate (whatever type Helm parsed it as)
  - .name: the value's own dotted path, for the error message (e.g. "manager.healthProbe.port")
Emits a bare integer as a string - callers pipe it through `| int` themselves.
*/}}
{{- define "candor.validatedPort" -}}
{{- $s := .value | toString }}
{{- if not (regexMatch "^-?(0|[1-9][0-9]{0,4})$" $s) }}
{{- fail (printf "%s must be an integer with no leading zeros and no more than 5 digits, got %q" .name $s) }}
{{- end }}
{{- $s | int }}
{{- end }}

{{/*
Resolves manager.webhookReceiver.port defensively, not via a plain dotted reference or Sprig's
`default` - the whole webhookReceiver block is dropped entirely (not reset to a default) on chart
regeneration (see CONTRIBUTING.md), and `default` treats an explicit 0 - this feature's own
documented "disabled" value, matching cmd/main.go's `signal-receiver-port > 0` flag semantics - as
empty and would silently override it back to 9444.

Used from every template that needs this port (charts/chart/templates/manager/manager.yaml,
charts/chart/templates/extras/webhook-receiver-service.yaml,
charts/chart/templates/network-policy/allow-webhook-signal-traffic.yaml) so the resolution logic
itself has one source of truth - three copies of this same snippet already proved capable of
drifting apart in review before this file existed.

Emits a bare integer as a string (via `include ... | int` at each call site) - "enabled" is left
for the caller to decide (`gt $whPort 0`, matching cmd/main.go's own check exactly, not just
`ne $whPort 0`, which would treat a negative value as enabled).
*/}}
{{- define "candor.webhookReceiverPort" -}}
{{- $port := 9444 }}
{{- /*
hasKey, not a truthy check on the value itself: `{{- if .Values.manager.webhookReceiver }}` is
false for the scalar value 0, so `--set manager.webhookReceiver=0` (a plausible fat-finger of the
real, one-level-deeper `.port` path) would silently keep the default port instead of failing loudly
via the kindIs check below - exactly the silent-coercion class this whole file exists to catch.
hasKey is true for any present value, including 0, so that check still runs.
*/}}
{{- if hasKey .Values.manager "webhookReceiver" }}
{{- if not (kindIs "map" .Values.manager.webhookReceiver) }}
{{- fail (printf "manager.webhookReceiver must be a map (e.g. {port: 9444}), got %q" (.Values.manager.webhookReceiver | toString)) }}
{{- end }}
{{- if hasKey .Values.manager.webhookReceiver "port" }}
{{- $port = include "candor.validatedPort" (dict "value" .Values.manager.webhookReceiver.port "name" "manager.webhookReceiver.port") | int }}
{{- end }}
{{- end }}
{{- $port }}
{{- end }}

{{/*
Reports whether an already-resolved port value (from candor.webhookReceiverPort, passed in as .)
means the feature it belongs to is enabled - centralized so every caller decides "enabled" the same
way (`gt`, not `ne`, so a negative value is treated as disabled the same as 0 - see
candor.webhookReceiverPort's own doc comment) instead of each of the three call sites repeating
the comparison itself, another copy that already proved capable of drifting independently.
Returns a non-empty string ("true") when enabled, empty otherwise - use as
`{{- if include "candor.portEnabled" $whPort }}`.
*/}}
{{- define "candor.portEnabled" -}}
{{- if gt (int .) 0 }}true{{- end }}
{{- end }}
